-- a
require "pcfields.plugins.autopairs"
-- b
require "pcfields.plugins.bufferline"
-- c
require "pcfields.plugins.cmp"
require "pcfields.plugins.colorscheme"
require "pcfields.plugins.comment"
-- d
require "pcfields.plugins.dap"
require "pcfields.plugins.dressing"
-- f
require "pcfields.plugins.fidget"
-- g
require "pcfields.plugins.gitsigns"
-- i
require "pcfields.plugins.indent-blankline"
-- l
require "pcfields.plugins.lsp-config"
require "pcfields.plugins.lualine"
-- m
require "pcfields.plugins.mason"
--n
require "pcfields.plugins.neo-tree"
require "pcfields.plugins.neodev"
require "pcfields.plugins.null-ls"
--t
require "pcfields.plugins.tabnine"
require "pcfields.plugins.telescope"
require "pcfields.plugins.toggleterm"
require "pcfields.plugins.treesitter"
require "pcfields.plugins.trouble"
require "pcfields.plugins.twilight"
-- w
require "pcfields.plugins.whick-key"